# Generated by Django 4.1.5 on 2023-08-04 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fecha_Partidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('latitud', models.CharField(max_length=100)),
                ('longitud', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia_Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('video', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='Promociones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_De_Comida_Imagen_Por_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_De_Comida_Unica_Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='Partidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('torneo', models.CharField(max_length=100)),
                ('equipo_1', models.CharField(max_length=100)),
                ('imagen_equipo1', models.ImageField(upload_to='imagenes/')),
                ('equipo_2', models.CharField(max_length=100)),
                ('imagen_equipo2', models.ImageField(upload_to='imagenes/')),
                ('hora', models.CharField(max_length=100)),
                ('fecha_del_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.fecha_partidos')),
            ],
        ),
        migrations.CreateModel(
            name='Comidas_Unica_Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.CharField(max_length=100)),
                ('Pertenece_A', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.tipos_de_comida_unica_imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Comidas_Imagen_Por_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('Pertenece_A', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.tipos_de_comida_imagen_por_producto')),
            ],
        ),
    ]
