# Generated by Django 4.1.5 on 2023-08-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fecha_partidos',
            name='nombre_en_admin',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
