# Generated by Django 4.1.5 on 2023-08-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_fecha_partidos_nombre_en_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fecha_partidos',
            name='fecha',
        ),
        migrations.AddField(
            model_name='fecha_partidos',
            name='año',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fecha_partidos',
            name='dia',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fecha_partidos',
            name='mes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
